### ISSUE TITLE
Login and authentication system 

### ISSUE THREAD

**Issue by goustkor** [Underground-Roleplay/framework#17]
I was checking and realized that you are using the HWID and socialID to generate an authentication.

However, I believe that this makes it very difficult to use the framework, as the documentation itself says that SocialId is very easy to spoof, and if you use the HWID it will make the player lose his account if he changes computers.

My idea would be a login panel when connecting to the city, which works with USER/PASS or integration with discord.

**Comment by nickplayz** [comment]
You can alter it by yourself for your own use, we use socialID, hwidHash and hwidEXHash in order to prevent others from spoof your "account" easily, we are aware about the socialID spoof, and HWID computer changes, but WE WILL NOT CREATE A LOGIN PANEL AT LEAST NOT FOR NOW, we are aiming to build a base for servers not a free server ready for production.
That said, feel free to contribute, build your own server using this framework as a base.
You can also use Stuyk's discord OAuth you just need to change some lines of code.
